version: '3.4'

services:

  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
     - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=mqadmin
     - RABBITMQ_DEFAULT_PASS=Admin123XX_

  rabbitmqdemo1.web:
    image: ${DOCKER_REGISTRY-}rabbitmqdemo1web
    build:
      context: .
      dockerfile: src/RabbitMQDemo1.Web/Dockerfile

  rabbitmqdemo1.microservice:
    image: ${DOCKER_REGISTRY-}rabbitmqdemo1microservice
    build:
      context: .
      dockerfile: src/RabbitMQDemo1.Microservice/Dockerfile